### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by AUnicornWithNoLife** [AUnicornWithNoLife/countdown#5]
dislikes safari on IOS

Tested on iPhone 5s, 16GB, 12.4.4, silver

**Comment by Redo-From-Start** [comment]
just outputs NaN Hours NaN Minutes NaN seconds till NaN

**Comment by Redo-From-Start** [comment]
i will try and fix this sometime soon... should be done within the next month, hopefully

**Comment by Redo-From-Start** [comment]
still cant fix this...

**Comment by Redo-From-Start** [comment]
this code runs fine on my mbp running 10.15

**Comment by Redo-From-Start** [comment]
i think it has something todo with post.php

**Comment by AUnicornWithNoLife** [comment]
This issue I think is cause by post data being added into redirects, I think if I fail redirect in mobile and make them click the link it should solve it
